(cl:defpackage sensor_msgs_ext-srv
  (:use )
  (:export
   "CALIBRATE_GYROSCOPE"
   "<CALIBRATE_GYROSCOPE-REQUEST>"
   "CALIBRATE_GYROSCOPE-REQUEST"
   "<CALIBRATE_GYROSCOPE-RESPONSE>"
   "CALIBRATE_GYROSCOPE-RESPONSE"
   "GET_PROXIMITY_CONFIGURATION"
   "<GET_PROXIMITY_CONFIGURATION-REQUEST>"
   "GET_PROXIMITY_CONFIGURATION-REQUEST"
   "<GET_PROXIMITY_CONFIGURATION-RESPONSE>"
   "GET_PROXIMITY_CONFIGURATION-RESPONSE"
   "SET_AXIS_HOME"
   "<SET_AXIS_HOME-REQUEST>"
   "SET_AXIS_HOME-REQUEST"
   "<SET_AXIS_HOME-RESPONSE>"
   "SET_AXIS_HOME-RESPONSE"
  ))

