// Generated by gencpp from file sensor_msgs_ext/calibrate_gyroscopeResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_MSGS_EXT_MESSAGE_CALIBRATE_GYROSCOPERESPONSE_H
#define SENSOR_MSGS_EXT_MESSAGE_CALIBRATE_GYROSCOPERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_msgs_ext
{
template <class ContainerAllocator>
struct calibrate_gyroscopeResponse_
{
  typedef calibrate_gyroscopeResponse_<ContainerAllocator> Type;

  calibrate_gyroscopeResponse_()
    : success(false)
    , message()  {
    }
  calibrate_gyroscopeResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct calibrate_gyroscopeResponse_

typedef ::sensor_msgs_ext::calibrate_gyroscopeResponse_<std::allocator<void> > calibrate_gyroscopeResponse;

typedef boost::shared_ptr< ::sensor_msgs_ext::calibrate_gyroscopeResponse > calibrate_gyroscopeResponsePtr;
typedef boost::shared_ptr< ::sensor_msgs_ext::calibrate_gyroscopeResponse const> calibrate_gyroscopeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator1> & lhs, const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator1> & lhs, const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_msgs_ext

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs_ext/calibrate_gyroscopeResponse";
  }

  static const char* value(const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success                # TRUE if the calibration was successful, otherwise FALSE.\n"
"string message              # If unsuccesful, reports the reason.\n"
;
  }

  static const char* value(const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calibrate_gyroscopeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_msgs_ext::calibrate_gyroscopeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MSGS_EXT_MESSAGE_CALIBRATE_GYROSCOPERESPONSE_H
