// Generated by gencpp from file sensor_msgs_ext/magnetometer.msg
// DO NOT EDIT!


#ifndef SENSOR_MSGS_EXT_MESSAGE_MAGNETOMETER_H
#define SENSOR_MSGS_EXT_MESSAGE_MAGNETOMETER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_msgs_ext
{
template <class ContainerAllocator>
struct magnetometer_
{
  typedef magnetometer_<ContainerAllocator> Type;

  magnetometer_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  magnetometer_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> const> ConstPtr;

}; // struct magnetometer_

typedef ::sensor_msgs_ext::magnetometer_<std::allocator<void> > magnetometer;

typedef boost::shared_ptr< ::sensor_msgs_ext::magnetometer > magnetometerPtr;
typedef boost::shared_ptr< ::sensor_msgs_ext::magnetometer const> magnetometerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_msgs_ext::magnetometer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_msgs_ext::magnetometer_<ContainerAllocator1> & lhs, const ::sensor_msgs_ext::magnetometer_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_msgs_ext::magnetometer_<ContainerAllocator1> & lhs, const ::sensor_msgs_ext::magnetometer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_msgs_ext

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::sensor_msgs_ext::magnetometer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs_ext/magnetometer";
  }

  static const char* value(const ::sensor_msgs_ext::magnetometer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A 3D measurement of the local magnetic field.\n"
"\n"
"float64 x           # The magnetic field strength in the X direction [T]\n"
"float64 y           # The magnetic field strength in the Y direction [T]\n"
"float64 z           # The magnetic field strength in the Z direction [T]\n"
;
  }

  static const char* value(const ::sensor_msgs_ext::magnetometer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct magnetometer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_msgs_ext::magnetometer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_msgs_ext::magnetometer_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MSGS_EXT_MESSAGE_MAGNETOMETER_H
