// Generated by gencpp from file sensor_msgs_ext/proximity.msg
// DO NOT EDIT!


#ifndef SENSOR_MSGS_EXT_MESSAGE_PROXIMITY_H
#define SENSOR_MSGS_EXT_MESSAGE_PROXIMITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_msgs_ext
{
template <class ContainerAllocator>
struct proximity_
{
  typedef proximity_<ContainerAllocator> Type;

  proximity_()
    : proximity(false)  {
    }
  proximity_(const ContainerAllocator& _alloc)
    : proximity(false)  {
  (void)_alloc;
    }



   typedef uint8_t _proximity_type;
  _proximity_type proximity;





  typedef boost::shared_ptr< ::sensor_msgs_ext::proximity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_msgs_ext::proximity_<ContainerAllocator> const> ConstPtr;

}; // struct proximity_

typedef ::sensor_msgs_ext::proximity_<std::allocator<void> > proximity;

typedef boost::shared_ptr< ::sensor_msgs_ext::proximity > proximityPtr;
typedef boost::shared_ptr< ::sensor_msgs_ext::proximity const> proximityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_msgs_ext::proximity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_msgs_ext::proximity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_msgs_ext::proximity_<ContainerAllocator1> & lhs, const ::sensor_msgs_ext::proximity_<ContainerAllocator2> & rhs)
{
  return lhs.proximity == rhs.proximity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_msgs_ext::proximity_<ContainerAllocator1> & lhs, const ::sensor_msgs_ext::proximity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_msgs_ext

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs_ext::proximity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs_ext::proximity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs_ext::proximity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs_ext::proximity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs_ext::proximity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs_ext::proximity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_msgs_ext::proximity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87ce68baa8581bc2125ed1ea8e240a58";
  }

  static const char* value(const ::sensor_msgs_ext::proximity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87ce68baa8581bc2ULL;
  static const uint64_t static_value2 = 0x125ed1ea8e240a58ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_msgs_ext::proximity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs_ext/proximity";
  }

  static const char* value(const ::sensor_msgs_ext::proximity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_msgs_ext::proximity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Reports the instantaneous measurement of a proximity sensor.\n"
"\n"
"bool proximity              # Reports TRUE if proximity is detected, otherwise FALSE.\n"
;
  }

  static const char* value(const ::sensor_msgs_ext::proximity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_msgs_ext::proximity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.proximity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct proximity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_msgs_ext::proximity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_msgs_ext::proximity_<ContainerAllocator>& v)
  {
    s << indent << "proximity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.proximity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MSGS_EXT_MESSAGE_PROXIMITY_H
