// Generated by gencpp from file sensor_msgs_ext/set_axis_home.msg
// DO NOT EDIT!


#ifndef SENSOR_MSGS_EXT_MESSAGE_SET_AXIS_HOME_H
#define SENSOR_MSGS_EXT_MESSAGE_SET_AXIS_HOME_H

#include <ros/service_traits.h>


#include <sensor_msgs_ext/set_axis_homeRequest.h>
#include <sensor_msgs_ext/set_axis_homeResponse.h>


namespace sensor_msgs_ext
{

struct set_axis_home
{

typedef set_axis_homeRequest Request;
typedef set_axis_homeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_axis_home
} // namespace sensor_msgs_ext


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_msgs_ext::set_axis_home > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sensor_msgs_ext::set_axis_home&) { return value(); }
};

template<>
struct DataType< ::sensor_msgs_ext::set_axis_home > {
  static const char* value()
  {
    return "sensor_msgs_ext/set_axis_home";
  }

  static const char* value(const ::sensor_msgs_ext::set_axis_home&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_msgs_ext::set_axis_homeRequest> should match
// service_traits::MD5Sum< ::sensor_msgs_ext::set_axis_home >
template<>
struct MD5Sum< ::sensor_msgs_ext::set_axis_homeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_msgs_ext::set_axis_home >::value();
  }
  static const char* value(const ::sensor_msgs_ext::set_axis_homeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_msgs_ext::set_axis_homeRequest> should match
// service_traits::DataType< ::sensor_msgs_ext::set_axis_home >
template<>
struct DataType< ::sensor_msgs_ext::set_axis_homeRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_msgs_ext::set_axis_home >::value();
  }
  static const char* value(const ::sensor_msgs_ext::set_axis_homeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_msgs_ext::set_axis_homeResponse> should match
// service_traits::MD5Sum< ::sensor_msgs_ext::set_axis_home >
template<>
struct MD5Sum< ::sensor_msgs_ext::set_axis_homeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_msgs_ext::set_axis_home >::value();
  }
  static const char* value(const ::sensor_msgs_ext::set_axis_homeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_msgs_ext::set_axis_homeResponse> should match
// service_traits::DataType< ::sensor_msgs_ext::set_axis_home >
template<>
struct DataType< ::sensor_msgs_ext::set_axis_homeResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_msgs_ext::set_axis_home >::value();
  }
  static const char* value(const ::sensor_msgs_ext::set_axis_homeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_MSGS_EXT_MESSAGE_SET_AXIS_HOME_H
