// Generated by gencpp from file sensor_msgs_ext/time_reference.msg
// DO NOT EDIT!


#ifndef SENSOR_MSGS_EXT_MESSAGE_TIME_REFERENCE_H
#define SENSOR_MSGS_EXT_MESSAGE_TIME_REFERENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_msgs_ext
{
template <class ContainerAllocator>
struct time_reference_
{
  typedef time_reference_<ContainerAllocator> Type;

  time_reference_()
    : utc_time()  {
    }
  time_reference_(const ContainerAllocator& _alloc)
    : utc_time()  {
  (void)_alloc;
    }



   typedef ros::Time _utc_time_type;
  _utc_time_type utc_time;





  typedef boost::shared_ptr< ::sensor_msgs_ext::time_reference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_msgs_ext::time_reference_<ContainerAllocator> const> ConstPtr;

}; // struct time_reference_

typedef ::sensor_msgs_ext::time_reference_<std::allocator<void> > time_reference;

typedef boost::shared_ptr< ::sensor_msgs_ext::time_reference > time_referencePtr;
typedef boost::shared_ptr< ::sensor_msgs_ext::time_reference const> time_referenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_msgs_ext::time_reference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_msgs_ext::time_reference_<ContainerAllocator1> & lhs, const ::sensor_msgs_ext::time_reference_<ContainerAllocator2> & rhs)
{
  return lhs.utc_time == rhs.utc_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_msgs_ext::time_reference_<ContainerAllocator1> & lhs, const ::sensor_msgs_ext::time_reference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_msgs_ext

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_msgs_ext::time_reference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msgs_ext::time_reference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msgs_ext::time_reference_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fec41e35208cc454786888579a04bcb";
  }

  static const char* value(const ::sensor_msgs_ext::time_reference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fec41e35208cc45ULL;
  static const uint64_t static_value2 = 0x4786888579a04bcbULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs_ext/time_reference";
  }

  static const char* value(const ::sensor_msgs_ext::time_reference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A time measurement from a timing source.\n"
"\n"
"time utc_time       # The measured UTC time.\n"
;
  }

  static const char* value(const ::sensor_msgs_ext::time_reference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.utc_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct time_reference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_msgs_ext::time_reference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_msgs_ext::time_reference_<ContainerAllocator>& v)
  {
    s << indent << "utc_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.utc_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MSGS_EXT_MESSAGE_TIME_REFERENCE_H
